steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/beth-personal-assistant/beth-assistant/backend:latest",
        ".",
      ]

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/beth-personal-assistant/beth-assistant/backend:latest",
      ]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "beth-assistant-backend"
      - "--image"
      - "us-central1-docker.pkg.dev/beth-personal-assistant/beth-assistant/backend:latest"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "2Gi"
      - "--set-env-vars"
      - "NOTION_TOKEN=secret_dummy_token,FIGMA_ACCESS_TOKEN=dummy_figma_token,GITHUB_TOKEN=dummy_github_token,OPENAI_API_KEY=dummy_openai_key"

images:
  - "us-central1-docker.pkg.dev/beth-personal-assistant/beth-assistant/backend:latest"
